### ISSUE TITLE
Specifica di stampa

### ISSUE THREAD

**Issue by tonyiovino** [tonyiovino/tipi_avanzati#1]
Qual è la specifica di stampa della variabile "double"?

**Comment by FabioZTessitore** [comment]
%f

**Comment by tonyiovino** [comment]
Sisi, lo so, intendevo nello "scan", ma mi avete già detto che è `"%lf"`

**Comment by FabioZTessitore** [comment]
Ok, però nel programma sono tutte sbagliate

**Comment by tonyiovino** [comment]
Ah, perfetto... Appena torno a casa, cerco di aggiustare.

Il Sab 16 Nov 2019 21:33 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
No, vabbeh... Come ho potuto fare un errore del genere?! HAHAHA
Invece di "`%d`" e "`%f`" avevo messo "`d%`" e "`f%`".
Ho risolto questo errore.
