### ISSUE TITLE
cast

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/tipi_avanzati#3]
il cast non lo hai fatto, hai solo messo l'assegnazione

**Comment by tonyiovino** [comment]
Non riesco a capire dove c'è l'errore.

**Comment by FabioZTessitore** [comment]
Non c'è il cast

Il sab 16 nov 2019, 16:16 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Eh, non ho capito bene come si fa, perché se lo faccio come sta scritto
nell'esempio dove lo spiega, durante la compilazione, me lo da come errore.

Il Sab 16 Nov 2019 20:04 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Non è che stai facendo confusione tra i linguaggi?

Il sab 16 nov 2019, 20:08 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Penso di no...

Il Sab 16 Nov 2019 20:11 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
d_user è già double, deve essere convertito in int

**Comment by tonyiovino** [comment]
Tipo se ho un intero, e voglio convertirlo in double, devo mettere quello
che deve essere convertito a sinistra?

Il Sab 16 Nov 2019 21:32 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
No. Tu hai un valore double (memorizzato in una variabile double) e lo vuoi
assegnare ad una variabile intera.
Per esempio:
int i;
double d = 3.2;

i = d;

Così come sta, il compilatore ti avvisa che c'è un possibile problema
(infatti ora i vale 3 e non 3.2).
Siccome è quello che volevamo, lo diciamo chiaramente con il cast.

i = (int)d;

Il sab 16 nov 2019, 21:54 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Sì, avevo fatto l'esempio, all'incontrario.
Ora ci provo.

Il Dom 17 Nov 2019 13:03 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
Okay, ci sono riuscito. Ora lo aggiungo a Github.
