### ISSUE TITLE
sumvett

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/tipi_avanzati#5]
attenzione al calcolo della media

**Comment by tonyiovino** [comment]
Cosa c'è di sbagliato? Gli indirizzi ai vettori?

**Comment by FabioZTessitore** [comment]
il vettore è uno solo e gli indirizzi delle varie celle sono utilizzati correttamente.
Ripeto: attenzione al calcolo della media

**Comment by tonyiovino** [comment]
Mh... Deve essere un float (?)

**Comment by FabioZTessitore** [comment]
ok, ma non basta
